### ISSUE TITLE
Not seeing the plugin

### ISSUE THREAD

**Issue by kphehe** [auxdesigner/Sketch-to-VR#4]
I followed the instructions, and I dropped the Sketch to VR folder into the plugin folder. However, after a few tries and restarting, I'm not able to see the Sketch to VR option in the Plugins menu.

**Comment by auxdesigner** [comment]
Yes. This is caused by the latest Sketch Plugin update: http://developer.sketchapp.com/introduction/plugin-bundles/
You should still be able to find it in the "Legacy plugin" menu option.
I will update the plugin shortly to the new structure so it will show up in the Plugins menu.

**Comment by auxdesigner** [comment]
This is done with the latest update.
